// <auto-generated />
using LabbOmFotbollAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabbOmFotbollAPI.Migrations
{
    [DbContext(typeof(ArenaDbModel))]
    [Migration("20210121144148_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("LabbOmFotbollAPI.Model.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stad")
                        .HasColumnType("TEXT");

                    b.Property<string>("arenaNamn")
                        .HasColumnType("TEXT");

                    b.Property<string>("landsKod")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arenas");
                });
#pragma warning restore 612, 618
        }
    }
}
